using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.Serialization;
using System.Threading.Tasks;
using MongoDB.Bson;
using MongoDB.Bson.Serialization.Attributes;
using RoleBased.API.Models;

namespace RoleBased.API.Entities
{
    public class User
    {
        [BsonId]
        // standard BSonId generated by MongoDb
        public ObjectId InternalId { get; set; }

        [DataMember]
        public string Id
        {
            get { return InternalId.ToString(); }
            set { InternalId = ObjectId.Parse(value); }
        }
       
        public string FirstName { get; set; }
       
        public string LastName { get; set; }
       
        public string PhoneNumber { get; set; }
       
        public string Email { get; set; }
        
        public string Username { get; set; }
      
        public string Password { get; set; }
       
        public string Role { get; set; }
        
        public string Token { get; set; }

        public List<Request> Requests { get; set; }
        public User()
        {
            Requests=new List<Request>();
        }
        
    }

}
